### ISSUE TITLE
Correggere classi

### ISSUE THREAD

**Issue by Meneghin98** [Meneghin98/TecWeb#22]
Rinominare le classi usate fin ora con quelle definite dalla documentazione

**Comment by nicoloGiaccone** [comment]
Corretti tutti le classi nei file html aggiornati

**Comment by Meneghin98** [comment]
corretti i file dell'area utente e della recensione di call of duty

**Comment by Meneghin98** [comment]
sono un coglione e l'avevo chiusa per sbaglio
