### ISSUE TITLE
Modello stampa

### ISSUE THREAD

**Issue by Meneghin98** [Meneghin98/TecWeb#29]

**Comment by TintoEdoardo** [comment]
Fatto una prima stesura, domani la completo

**Comment by TintoEdoardo** [comment]
Completato il layout di stampa. 
Per quanto riguarda il tag link nella sezione head consiglio di utilizzare media="screen" in tutti i tag. 
Senza questa specifica, nel momento in cui avviene la stampa, il browser cerca in tutti i fogli di stile linkati i riferimenti più specifici ai vari tag html.
