### ISSUE TITLE
Aggiungere aiuti alla navigazione

### ISSUE THREAD

**Issue by Meneghin98** [Meneghin98/TecWeb#32]
commentare se serve qualche aiuto particolare

**Comment by TintoEdoardo** [comment]
Ho aggiunto una classe _screenReaderHelper_ i cui elementi vengono sposati oltre i bordi della pagina, così da poter implementare gli aiuti alla navigazione per utenti non vedenti (restano ancora da fare aiuti generici, per esempio un link torna in alto). 

Se usate questa classe è sufficiente inserire il relativo tag html nell'ordine in cui si vuole venga letto, la gestione del relativo elemento a video è già implementata.

**Comment by Meneghin98** [comment]
Implementare:
- vai al contenuto (saltare il menu)
- torna su

**Comment by Meneghin98** [comment]
- utilities (search & login)

**Comment by nicoloGiaccone** [comment]
Implementato link torna su "dinamico", su tutte le pagine in cui è necessario
