### ISSUE TITLE
Footer rotto

### ISSUE THREAD

**Issue by Meneghin98** [Meneghin98/TecWeb#36]
Qualcosa ha "rotto" il footer, ho già risolto alcuni problemi, però sarebbe meglio controllare meglio dato che alcune cose non mi risultano molto intuitive (ci sono due regole .footer nel css, wtf)

**Comment by TintoEdoardo** [comment]
Ho controllato il footer, il punto di rottura non è nel footer ma nella lista di articoli. 
Ho ripulito dal codice superfluo, vi aggiorno a breve
