### ISSUE TITLE
Rivalutare il menu

### ISSUE THREAD

**Issue by Meneghin98** [Meneghin98/TecWeb#39]
Com'è ora, potrebbe dare problemi a persone ipovedenti
Opzioni:
- Ridimensionarlo: ci sono pochi link, per cui se invece di fargli occupare tutta la pagina lo riduciamo, avvicinando così le schede, risulta più facile la navigazione (si sacrifica un po' di estetica)
- Renderlo verticale: in questo caso specificare nella relazione il motivo per cui si è scelto questo approccio, mostrando anche tramite screenshot la precedente versione

**Comment by TintoEdoardo** [comment]
Secondo me la seconda scelta è la migliore. 
L'idea di una screenshot mi sembra ottima, sicuramente aiuta a motivare nella relazione. 
Provo a fornire un'implementazione di prova, che inserisco nel branch Design Elastico.

**Comment by Meneghin98** [comment]
lo screenshot l'ha suggerito la professoressa, comunque per discuterne scrivi sull'altra issue, questa la teniamo per l'implementazione

**Comment by nicoloGiaccone** [comment]
Secondo me sarebbe meglio  fare il contrario nel senso, qui che abbiamo esposto le opzioni discutiamo sulle due opzioni, mentre nell'altra ed eventualmente nella seconda si può discutere dell'implementazione di quel singolo metodo

**Comment by Meneghin98** [comment]
come volete
