### ISSUE TITLE
Rottura file recensioneDeadStranding

### ISSUE THREAD

**Issue by Meneghin98** [Meneghin98/TecWeb#40]
Sembrerebbe che il file non sia collegato ad un css
Inoltre sembra seguire ancora la vecchia definizione (l'header non è stato aggiornato a quello nuovo, forse c'è anche altro..)

**Comment by nicoloGiaccone** [comment]
Questo è perché da quando è stato creato il file non è stato più toccato infatti e ancora la recensione di vampiri se non sbaglio

**Comment by Meneghin98** [comment]
Cosa bisogna fare quindi con questo file?
è da implementare una recensione o va eliminato?

**Comment by EnricoSalmaso** [comment]
Tutto sistemato Simone.
