### ISSUE TITLE
Implementazione nuovo menu

### ISSUE THREAD

**Issue by nicoloGiaccone** [Meneghin98/TecWeb#41]
# Menù orizzontale di dimensione minore
Ho fatto un prim0 test per implemnetare il menù come suggerito dalla professoressa, per il momento ho pensato a due soluzioni:
- Dare un max-width all'elenco di (ad esempio 640px) e poi metterci attorno un div per darci un background, che altrimenti rimarebbe vuoto, non ho implementato quest'idea perchè avrei creato una struttura html solo ed esclusivamente per l'estetica.
- Mettere dei bordi destro e sinistro di ad esempio (250 px, per avere un menu di 640px), questa soluzione mi sempre migliore ad una prima occhiata, però index css mi va a creare un conflitto (se andate e vedere i css vedrete che ho creato un id per la home, solo a scopo illustrativo), in quanto su home il bordo lo fa interno al ul ossia dalla max-widith restringe il menù, mentre nelle altre pagine il  bordo lo fa all'esterno...

Ditemi cosa ne pensate di queste due soluzioni e se ne trovate di migliori proveremmo ad implementarle.  Spero di avere spiegato i miei dubbi.
Per la prima soluzione ho fatto un veloce test sulla elasticità ma vorrei verificarne meglio quando abbiamo deciso come implementarla, mentre per la seconda no qundi bisognerà verificare anche quello

**Comment by Meneghin98** [comment]
Avevo già aperto una issue per il menu, quindi dimmi te quale tenere
Se si volesse optare per una versione verticale avevo pensato di fare un menu "stiky", magari valutando di allargare il max-width del contenuto della pagina per evitare che risulti il tutto troppo "stretto"
Domani provvedo a creare un feature branch dove possiamo testare le idee

**Comment by nicoloGiaccone** [comment]
Yep lo so, però mi sembrava una cosa più diretta mettere una issue diversa, comunque se vuoi sposto la issue come commento alla tua e questa la chiudo

**Comment by Meneghin98** [comment]
no no va bene allora, teniamo questa come riferimento per la discussione e l'altra per l'implementazione

**Comment by TintoEdoardo** [comment]
Secondo me farlo verticale è la cosa migliore. 
Provo a implementare una versione ora. 
Domani possiamo valutare il risultato, l'html secondo me è ben fatto, penso modificherò esclusivamente il css. 
Provo nel branch Design Elastico
