### ISSUE TITLE
Discursione link circolari (con PHP)

### ISSUE THREAD

**Issue by nicoloGiaccone** [Meneghin98/TecWeb#44]
Sistemare la possibile situazione di link circolari

**Comment by Meneghin98** [comment]
La soluzione in realtà è abbastanza semplice, purtroppo però non è bella…
Per capirci nel file replace.php (branch feature-php) è presente la funzione per attaccare il menu a tutte le pagine e come notate è un pugno nell'occhio, però funziona...
