### ISSUE TITLE
Rendere dinamico pannello laterale

### ISSUE THREAD

**Issue by Meneghin98** [Meneghin98/TecWeb#72]

**Comment by nicoloGiaccone** [comment]
Ho fatto una prima implementazione del rightPanel dinamico, ora è inserito dinamicamente in tutte le pagine. Ora devo implementare la funzione che ritorna i 3 articoli più letti.

**Comment by nicoloGiaccone** [comment]
Finito di implementare il pannello laterale dinamicamente, ora anche le notizie sono inserite via php
