### ISSUE TITLE
Rendere dinamico il menu (se possibile)

### ISSUE THREAD

**Issue by Meneghin98** [Meneghin98/TecWeb#74]
se si è trovata una soluzione per il footer, applicarla anche al menu

**Comment by TintoEdoardo** [comment]
Il menu è stato implementato sulle pagine news, recensioni, altro e su un articolo di prova (quello sui monitor). 
Il menu funziona, è sufficiente sostituire al div menu il segnaposto £menu_ per tutti gli articoli e l'index
