### ISSUE TITLE
Completare la sezione commenti

### ISSUE THREAD

**Issue by Meneghin98** [Meneghin98/TecWeb#77]
Manca la funzionalità di like tra commenti, implementabili tramite javascript (consigio: ajax) e la possibilità di followare (non ricordo cosa, credo gli editori)
In oltre bisogna rimuovere gli spazi all'inizio e alla fine del commento

**Comment by nicoloGiaccone** [comment]
@Meneghin98 In teoria i follow erano sugli argomenti, ad esempio una persona segue la caregoria videogiochi-pc e quand esce una notizia relativa a quella categoria gli arriva una notifica se non sbaglio

**Comment by Meneghin98** [comment]
@nicoloGiaccone Ok ottimo grazie

**Comment by Meneghin98** [comment]
Consiglio: usare addslashes($commento) per non rompere la query
