### ISSUE TITLE
Chiedere alla prof se togliere l'effetto sulla scritta Decrypted Games

### ISSUE THREAD

**Issue by EnricoSalmaso** [Meneghin98/TecWeb#78]
La scritta Decrypted Games potrebbe portare confusione nell'utente (perchè nella home non si verifica nessun effetto alla scritta Decrypted Games, mentre nelle altre pagine si??)
Lo teniamo o lo togliamo?
CHIEDERE ALLA PROF

**Comment by nicoloGiaccone** [comment]
Ho chiesto ad alcune persone e mi hanno confermato che è meglio unificare lo stile, tanto che un link lo si capisce per convenzione e perchè cambia il curosre, quindi rimaniamo come siamo ora senza transizioni
