### ISSUE TITLE
Correggere path immagini articoli, e mettere gli alt a tutte le immagini

### ISSUE THREAD

**Issue by nicoloGiaccone** [Meneghin98/TecWeb#92]
Ci alcuni articoli che hanno i path delle immagini sbagliati e quindi non vengono visializzate, inoltre bisogna mettere gli alt a tutte le immagine dato che in alcune manca. Dobbiamo anche mettere gli alt nelle immagini sul database

**Comment by Meneghin98** [comment]
I path delle immagini dovrebbero essere stati corretti tutti

**Comment by Meneghin98** [comment]
come anche gli alt alle immagini, manca da inserirle solo sul file sql

**Comment by nicoloGiaccone** [comment]
@Meneghin98 Si penso di si, ma direi di aspettare un feedback da parte di tutti per esserne sicuri
